# Blender

## Rotation formalisms

See [Rotation formalisms in three dimensions](https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions). Blender's user interface only allows for rotations to be entered as as Quaternions, Euler rotations, or an Euler axis-angle. If you have a rotation in some other form, how do you enter it in Blender? See [Rotation — SciPy Manual](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html#scipy.spatial.transform.Rotation):

In [91]:
import numpy as np
from scipy.spatial.transform import Rotation as R

def show_rot(rot: R):
    print('Matrix:')
    display(rot.as_matrix())
    print('\nBlender "Quaternion":')
    display(rot.as_quat(canonical=True, scalar_first=True))
    print('\nBlender "XYZ Euler":')
    display(rot.as_euler('xyz', degrees=True))
    print('\nBlender "Axis Angle":')
    rot_vec = rot.as_rotvec(degrees=True)
    norm = np.linalg.norm(rot_vec)
    display(norm, rot_vec / norm)

In [90]:
show_rot(R.from_matrix([
[ 0.000, -0.643, -0.766],
[ 0.000, -0.766,  0.643],
[-1.000,  0.000,  0.000],]))

Matrix:


array([[-2.77555756e-17, -6.42962682e-01, -7.65897506e-01],
       [ 0.00000000e+00, -7.65897506e-01,  6.42962682e-01],
       [-1.00000000e+00,  0.00000000e+00, -2.77555756e-17]])


Blender "Quaternion":


array([ 0.2419207 , -0.66443538,  0.2419207 ,  0.66443538])


Blender "XYZ Euler":


array([-139.98690433,   90.        ,    0.        ])


Blender "Axis Angle":


np.float64(152.00014158445592)

array([-0.68477595,  0.24932669,  0.68477595])

In [88]:
show_rot(R.from_matrix([
[ 0.000,  0.000,  1.000],
[-1.000,  0.000,  0.000],
[ 0.000, -1.000,  0.000],]))

Matrix:


array([[ 0.,  0.,  1.],
       [-1.,  0.,  0.],
       [ 0., -1.,  0.]])


Blender "Quaternion":


array([ 0.5, -0.5,  0.5, -0.5])


Blender "XYZ Euler":


array([-90.,   0., -90.])


Blender "Axis Angle":


np.float64(119.99999999999999)

See also [Rotation Modes - Blender 4.5 LTS Manual](https://docs.blender.org/manual/en/latest/advanced/appendices/rotations.html). Many Blender tutorials try to explain Gimbal lock, but the best references still seem to be [Euler (gimbal lock) Explained - YouTube](https://www.youtube.com/watch?v=zc8b2Jo7mno) and [Gimbal lock - Wikipedia](https://en.wikipedia.org/wiki/Gimbal_lock).

In Eigen, quaternion-vector multiplication is [just multiplication](https://stackoverflow.com/a/52239772/622049). In Eigen the coeffs command [produces XYZW](https://eigen.tuxfamily.org/dox/classEigen_1_1QuaternionBase.html#a193e79f616335a0067e3e784c7cf85fa), but internally the data is XYZW. If you [install the Eigen pretty printers](https://stackoverflow.com/a/25088214/622049), it's explicit:
```
$1 = Eigen::Quaternion<double> (data ptr: 0x7fffffffd7d0) = {[x] = 0, [y] = 0.7071067811865841, [z] = 0, [w] = 0.70710678118651094}
```